(setq my-package-list '
      (
       emoji-fontset
       emojify
       ht
       seq
       ac-etags
       auto-complete
       popup
       aggressive-indent
       alert
       log4e
       gntp
       anything
       anzu
       async
       avy
       avy-zap
       cider
       spinner
       queue
       pkg-info
       epl
       clojure-mode
       circe
       clj-refactor
       hydra
       inflections
       edn
       s
       peg
       dash
       multiple-cursors
       paredit
       yasnippet
       coffee-mode
       color-theme-sanityinc-tomorrow
       company
       diff-hl
       diminish
       dired+
       easy-kill
       elixir-mode
       emmet-mode
       enh-ruby-mode
       exec-path-from-shell
       f
       flx
       flx-ido
       flycheck
       let-alist
       geiser
       gh
       logito
       pcache
       git-commit
       with-editor
       grizzl
       guru-mode
       helm
       helm-core
       helm-ag
       helm-descbinds
       helm-gtags
       helm-projectile
       projectile
       helm-robe
       hungry-delete
       ido-completing-read+
       ido-ubiquitous
       inf-ruby
       js2-mode
       js2-refactor
       json-mode
       json-snatcher
       json-reformat
       key-chord
       leuven-theme
       magit
       magit-popup
       markdown-mode
       names
       org
       polymode
       projectile-rails
       rake
       rich-minority
       robe
       rspec-mode
       rubocop
       ruby-refactor
       ruby-tools
       smart-mode-line
       smart-mode-line-powerline-theme
       powerline
       smartparens
       smex
       solarized-theme
       tern
       tern-auto-complete
       tree-mode
       web-mode
       which-key
       yaml-mode
       zenburn-theme
       emoji-display
       4clojure
       request
       ac-emmet
       ace-jump-buffer
       ace-jump-mode
       ace-window
       anything-exuberant-ctags
       auto-complete-exuberant-ctags
       auto-highlight-symbol
       back-button
       persistent-soft
       list-utils
       ucs-utils
       smartrep
       nav-flash
       browse-kill-ring
       chronos
       clojure-snippets
       color-theme-solarized
       color-theme
       ctags
       dired-details+
       dired-details
       dired-efap
       dirtree
       windata
       discover-clj-refactor
       discover
       makey
       discover-my-major
       ecb
       edit-server-htmlize
       edit-server
       elisp-slime-nav
       eshell-did-you-mean
       eshell-prompt-extras
       expand-region
       fancy-battery
       flymake-ruby
       flymake-easy
       gist
       git-messenger
       git-timemachine
       gitconfig-mode
       gitignore-mode
       god-mode
       hackernews
       helm-emmet
       helm-git-grep
       hyde
       jsx-mode
       kibit-helper
       mmm-mode
       move-text
       noctilux-theme
       operate-on-number
       org-gcal
       request-deferred
       deferred
       ov
       php-mode
       prodigy
       projectile-speedbar
       rainbow-delimiters
       rainbow-mode
       ruby-additional
       ruby-electric
       ruby-hash-syntax
       s-buffer
       noflet
       scss-mode
       smartscan
       sr-speedbar
       string-inflection
       sublime-themes
       thesaurus
       undo-tree
       vkill
       volatile-highlights
       w3
       wisp-mode
       wispjs-mode
       zop-to-char))

(mapc #'package-install my-package-list)
